###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://sap.github.io/jenkins-library/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  inferBuildTool: true
  productiveBranch: 'master'
  gitSshKeyCredentialsId: 'git_id_pat'            ##Secret Text - Personal access token
  gitHttpsCredentialsId: 'github_credential_id'   ##username with password
  artifactPrepareVersion: false
  buildTool: 'mta'
  


### Step-specific configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  testsPublishResults:
    junit: [allowEmptyResults:true, testResults:**/target/surefire-reports/*.xml]
    jacoco: [pattern:**/target/coverage-reports/*.exec, allowEmptyResults:true, archive:false, active:false]

  artifactPrepareVersion:
    versioningType: cloud_noTag
  
  sonarExecuteScan:
    sonarTokenCredentialsId: 'sonarId'
    serverUrl: 'https://sonar.tools.sap/'
  
  mavenExecuteStaticCodeChecks:
    spotBugs: false
  
  fortifyExecuteScan:
    buildTool: 'maven'
    projectName: 'books-demo-service'
    serverUrl: 'https://fortify.tools.sap/ssc'
    dockerImage: 'docker.wdf.sap.corp:50000/piper/fortify:jdk11'
    fortifyCredentialsId: 'fortifyToken'
    src:
      - '**/src/main/java/**/*'
    exclude: ['**/target/**/*', '**/src/test/**/*']


### Stage-specific configuration
stages:
  'Build':
    mavenExecuteStaticCodeChecks: true
    npmExecuteLint: true
  
  'Integration':
    installArtifacts: true
    testsPublishResults:
      junit: [allowEmptyResults:true, testResults:**/integration-tests/target/surefire-reports/*.xml]
      jacoco: [pattern:**/target/coverage-reports/ITJacoco.exec, allowEmptyResults:true, archive:false, active:false]


  'Confirm':
    manualConfirmation: true
     manualConfirmationMessage: 'Shall we proceed to Promote & Release?'
     manualConfirmationTimeout: 1

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

#  Release:
#    cfTargets:
#      - org: 'myOrg'
#        space: 'mySpace'
#        apiEndpoint: 'https://'
#        appName: 'myAppName'
#        manifest: 'manifest.yml'
#        credentialsId: 'myDeploymentCredentialsId'
